// Generated by Wrangler on Sat Sep 14 2024 14:52:30 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	R2_ENDPOINT: string;
	R2_ACCESS_KEY: string;
	R2_SECRET_KEY: string;
}
